connection_throttle_limit: 3
timeout: 30000
online_mode: false
log_commands: true
network_compression_threshold: 256
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 100
  tab_size: 60
  force_default_server: false
connection_throttle: 4000
groups:
  md_5:
  - admin
  NaruseII:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
forge_support: false
inject_commands: false
disabled_commands:
- disabledcommandhere
stats: bfc97cb8-7b8f-4b37-b186-d9b9c237b3bc
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - auth.login
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
player_limit: -1
